services:
  # PostgreSQL Database
  postgres:
    image: postgres:17-alpine
    container_name: sportshub-postgres
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/prisma/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sportshub-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME:-sportshub}-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: ${BACKEND_PORT:-5000}
      HOST: ${BACKEND_HOST:-0.0.0.0}
    ports:
      - "${BACKEND_PORT:-5000}:${BACKEND_PORT:-5000}"
    depends_on:
      - postgres
    networks:
      - sportshub-network
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: ${BACKEND_COMMAND:-npm run dev}

volumes:
  postgres_data:


networks:
  sportshub-network:
    driver: bridge
